name: Update packages

on:
  workflow_dispatch:

jobs:
  update_packages:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ssh-known-hosts: 'aur.archlinux.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLMiLrP8pVi5BFX2i3vepSUnpedeiewE5XptnUnau+ZoeUOPkpoCgZZuYfpaIQfhhJJI5qgnjJmr4hyJbe/zxow='
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install deps
      run: python -m pip install --upgrade pip requests
    - name: Run updater script
      run: python update_pkgbuilds.py
