name: Update packages

on:
  workflow_dispatch:

jobs:
  update_packages:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ssh-known-hosts: 'aur.archlinux.org'
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
