name: edgedb-cli
on:
  push:
    paths:
      - 'edgedb-cli'

jobs:
  build:
    name: Build package from AUR
    runs-on: ubuntu-latest
    steps:
      - name: Build edgedb-cli package
        uses: DuckSoft/build-aur-action@master
        with:
          repo-name: edgedb-cli
