name: Test building clap

on:
  workflow_dispatch:

jobs:
  test_clap:
    name: Test building clap
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Test package can be built
      uses: 2m/arch-pkgbuild-builder@v1.16
      with:
        target: 'pkgbuild'
        pkgname: 'testing'
