name: Update routahe

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 0'

jobs:
  update_routahe:
    name: Update routahe
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Clone repo from AUR
      run: git clone https://aur.archlinux.org/routahe.git
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install deps
      run: python -m pip install --upgrade pip requests packaging
    - name: Check for updates and update PKGBUILD if there's an update available
      id: update_check
      run: |
        python update_pkgbuilds.py routahe
        echo "UPDATE_AVAILABLE=$UPDATE_AVAILABLE" >> $GITHUB_ENV
    - name: Test package can be built
      uses: 2m/arch-pkgbuild-builder@v1.16
      with:
        target: 'pkgbuild'
        pkgname: 'routahe'
      if: ${{ env.UPDATE_AVAILABLE == 'TRUE' }}
    - name: Test installed package is ok
      uses: 2m/arch-pkgbuild-builder@v1.16
      with:
        target: 'run'
        pkgname: 'routahe'
        command: 'routahe'
      if: ${{ env.UPDATE_AVAILABLE == 'TRUE' }}
    - name: Publish AUR package
      uses: KSXGitHub/github-actions-deploy-aur@v2.2.4
      with:
        pkgname: 'routahe'
        pkgbuild: 'routahe/PKGBUILD'
        commit_username: 'otahontasupdater'
        commit_email: 'aurupdater@ottoahoniemi.fi'
        commit_message: "Bump version"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        allow_empty_commits: false
        ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
      if: ${{ env.UPDATE_AVAILABLE == 'TRUE' }}
